### ISSUE TITLE
'repo' entries highlight keyword 'repo' and the first repository, but not additional repositories

### ISSUE THREAD

**Issue by acr4** [llloret/gitolite-emacs#4]
When specifying multiple repositories on a single line, the first repository is fontified the same as the keyword 'repo', but subsequent repositories receive no font-lock.  

![image](https://cloud.githubusercontent.com/assets/1616233/15361042/f9c4965a-1cdd-11e6-9d93-9929079132df.png)

Should all repository names be colored, or should none?  I'm inclined to think that none should be colored, as that allows the 'repo' keyword to take precedence.

I can work on a fix if you provide guidance on your preferred highlighting.

**Comment by llloret** [comment]
What do you think? I kind of like the idea of all the repo names being highlighted, but I am not sure how hard that would be...

**Comment by llloret** [comment]
Oh, and BTW, thanks a lot for taking time to improve this. I hadn't touched it for a while...
